language: android
jdk: openjdk11
sudo: required
dist: xenial

before_install:
  - yes | sdkmanager --licenses
  - sdkmanager "platforms;android-29" "build-tools;29.0.3"

install:
  - pip install python-for-android kivy

script:
  - p4a apk --private ./ --package org.example.scanner --name MyScannerApp --version 0.1 --requirements kivy,opencv-python-headless,pytesseract

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: path/to/your_apk_file.apk
  skip_cleanup: true
  on:
    tags: true